# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Suwan Jang
baseurl:        ""
url:            "http://www.suwanjang.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Suwan Jang
  url:          http://suwanjang.com/
  email:        jsuwan961205@gmail.com
  github:       jsuwan961205

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/jsuwan961205/jsuwan961205.github.io
